# Generated by Django 4.2.30 on 2026-05-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=200, verbose_name='Название привычки')),
                ('dates_completed', models.JSONField(default=list, verbose_name='Даты выполнения')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('transaction_type', models.CharField(choices=[('income', 'Доход'), ('expense', 'Расход')], max_length=10, verbose_name='Тип транзакции')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('description', models.CharField(blank=True, default='', max_length=300, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeekArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_key', models.CharField(max_length=100, unique=True, verbose_name='Ключ недели')),
                ('start_date', models.DateField(verbose_name='Дата начала недели')),
                ('end_date', models.DateField(verbose_name='Дата окончания недели')),
                ('tasks_data', models.JSONField(default=list, verbose_name='Данные задач')),
                ('total_tasks', models.IntegerField(default=0, verbose_name='Всего задач')),
                ('completed_tasks', models.IntegerField(default=0, verbose_name='Выполнено задач')),
                ('progress_percent', models.IntegerField(default=0, verbose_name='Процент выполнения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Архив недели',
                'verbose_name_plural': 'Архивы недель',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='WeekTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('task_id', models.CharField(max_length=50, unique=True, verbose_name='ID задачи')),
                ('date', models.DateField(verbose_name='Дата задачи')),
                ('text', models.CharField(max_length=500, verbose_name='Текст задачи')),
                ('is_done', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('time_start', models.TimeField(blank=True, null=True, verbose_name='Время начала')),
                ('time_end', models.TimeField(blank=True, null=True, verbose_name='Время окончания')),
            ],
            options={
                'verbose_name': 'Задача недели',
                'verbose_name_plural': 'Задачи недели',
                'ordering': ['date', 'time_start'],
            },
        ),
    ]
